from __future__ import annotations

from orbits_env.models import ConjunctionEvent, GeometryTag, TaskConfig


TASKS: dict[str, TaskConfig] = {
    "collision_avoidance_easy": TaskConfig(
        task_id="collision_avoidance_easy",
        difficulty="easy",
        description="Single high-confidence threat with enough fuel to maneuver conservatively.",
        horizon=6,
        initial_fuel=9.5,
        initial_tracking_quality=0.82,
        tracking_budget=2,
        visible_event_limit=2,
        fuel_cost_tracking=0.1,
        maneuver_base_cost=0.35,
        maneuver_variable_cost=0.55,
        tracking_improvement=0.16,
        tracking_decay=0.04,
        uncertainty_reduction_factor=0.55,
        passive_offset_recovery=0.1,
        mission_offset_penalty_weight=0.18,
        fuel_penalty_weight=0.16,
        risk_reduction_reward_weight=0.95,
        tracking_reward_weight=0.18,
        unsafe_probability_threshold=0.62,
        success_probability_threshold=0.18,
        max_total_offset_km=2.4,
        completion_bonus=0.25,
        collision_penalty=0.0,
        conjunctions=[
            ConjunctionEvent(
                object_id="deb-001",
                geometry_tag=GeometryTag.RADIAL_DOMINANT,
                collision_probability=0.34,
                predicted_miss_distance_km=1.25,
                time_to_closest_approach=4,
                uncertainty=0.12,
                radial_effectiveness=0.86,
                along_track_effectiveness=0.38,
                normal_effectiveness=0.44,
                risk_growth_rate=0.06,
                tracking_sensitivity=0.45,
            )
        ],
    ),
    "collision_avoidance_medium": TaskConfig(
        task_id="collision_avoidance_medium",
        difficulty="medium",
        description="Two conjunctions with different maneuver geometry and a tighter fuel budget.",
        horizon=8,
        initial_fuel=8.0,
        initial_tracking_quality=0.68,
        tracking_budget=2,
        visible_event_limit=3,
        fuel_cost_tracking=0.14,
        maneuver_base_cost=0.42,
        maneuver_variable_cost=0.62,
        tracking_improvement=0.18,
        tracking_decay=0.055,
        uncertainty_reduction_factor=0.5,
        passive_offset_recovery=0.08,
        mission_offset_penalty_weight=0.22,
        fuel_penalty_weight=0.2,
        risk_reduction_reward_weight=1.0,
        tracking_reward_weight=0.22,
        unsafe_probability_threshold=0.58,
        success_probability_threshold=0.24,
        max_total_offset_km=2.1,
        completion_bonus=0.28,
        collision_penalty=0.0,
        conjunctions=[
            ConjunctionEvent(
                object_id="deb-101",
                geometry_tag=GeometryTag.ALONG_TRACK_DOMINANT,
                collision_probability=0.27,
                predicted_miss_distance_km=1.55,
                time_to_closest_approach=5,
                uncertainty=0.2,
                radial_effectiveness=0.36,
                along_track_effectiveness=0.82,
                normal_effectiveness=0.48,
                risk_growth_rate=0.055,
                tracking_sensitivity=0.55,
            ),
            ConjunctionEvent(
                object_id="deb-102",
                geometry_tag=GeometryTag.RADIAL_DOMINANT,
                collision_probability=0.23,
                predicted_miss_distance_km=1.7,
                time_to_closest_approach=6,
                uncertainty=0.24,
                radial_effectiveness=0.74,
                along_track_effectiveness=0.34,
                normal_effectiveness=0.42,
                risk_growth_rate=0.05,
                tracking_sensitivity=0.48,
            ),
        ],
    ),
    "collision_avoidance_hard": TaskConfig(
        task_id="collision_avoidance_hard",
        difficulty="hard",
        description="Three competing threats with poor initial certainty and tight mission-offset limits.",
        horizon=10,
        initial_fuel=7.2,
        initial_tracking_quality=0.57,
        tracking_budget=3,
        visible_event_limit=3,
        fuel_cost_tracking=0.16,
        maneuver_base_cost=0.44,
        maneuver_variable_cost=0.7,
        tracking_improvement=0.2,
        tracking_decay=0.07,
        uncertainty_reduction_factor=0.45,
        passive_offset_recovery=0.06,
        mission_offset_penalty_weight=0.26,
        fuel_penalty_weight=0.22,
        risk_reduction_reward_weight=1.04,
        tracking_reward_weight=0.25,
        unsafe_probability_threshold=0.54,
        success_probability_threshold=0.28,
        max_total_offset_km=1.9,
        completion_bonus=0.3,
        collision_penalty=0.0,
        conjunctions=[
            ConjunctionEvent(
                object_id="deb-201",
                geometry_tag=GeometryTag.ALONG_TRACK_DOMINANT,
                collision_probability=0.24,
                predicted_miss_distance_km=1.45,
                time_to_closest_approach=4,
                uncertainty=0.3,
                radial_effectiveness=0.33,
                along_track_effectiveness=0.81,
                normal_effectiveness=0.4,
                risk_growth_rate=0.07,
                tracking_sensitivity=0.62,
            ),
            ConjunctionEvent(
                object_id="deb-202",
                geometry_tag=GeometryTag.NORMAL_DOMINANT,
                collision_probability=0.21,
                predicted_miss_distance_km=1.6,
                time_to_closest_approach=7,
                uncertainty=0.26,
                radial_effectiveness=0.38,
                along_track_effectiveness=0.29,
                normal_effectiveness=0.84,
                risk_growth_rate=0.055,
                tracking_sensitivity=0.5,
            ),
            ConjunctionEvent(
                object_id="deb-203",
                geometry_tag=GeometryTag.RADIAL_DOMINANT,
                collision_probability=0.19,
                predicted_miss_distance_km=1.8,
                time_to_closest_approach=5,
                uncertainty=0.32,
                radial_effectiveness=0.78,
                along_track_effectiveness=0.36,
                normal_effectiveness=0.41,
                risk_growth_rate=0.06,
                tracking_sensitivity=0.58,
            ),
        ],
    ),
}


def get_task(task_id: str) -> TaskConfig:
    try:
        return TASKS[task_id].model_copy(deep=True)
    except KeyError as exc:
        raise ValueError(f"Unknown task_id: {task_id}") from exc
